export const MOCK_JOBS = [
  {
    id: 'mock-j1',
    title: 'Macro Cell Tower Installation',
    company_name: 'AT&T Wireless',
    project_name: 'ATT-TX-2026-Q1',
    site_name: 'Tower Site Alpha-7',
    site_address: '1200 Industrial Blvd, Austin TX 78701',
    contact_name: 'Marcus Webb',
    contact_phone: '512-555-0192',
    scheduled_date: '2026-03-16',
    scheduled_time: '08:00',
    status: 'in_progress',
    priority: 'urgent',
    progress: 65,
    deliverables_remaining: 3,
    sync_status: 'synced',
    in_geofence: true,
    assigned_to: 'j.smith@purpulse.com',
    assigned_name: 'J. Smith',
  },
  {
    id: 'mock-j2',
    title: 'Rooftop DAS Deployment',
    company_name: 'Verizon Business',
    project_name: 'VZN-IL-Q1-DAS',
    site_name: 'Marquette Tower',
    site_address: '350 N Orleans St, Chicago IL 60654',
    contact_name: 'Sandra Liu',
    contact_phone: '312-555-0847',
    scheduled_date: '2026-03-16',
    scheduled_time: '10:30',
    status: 'en_route',
    priority: 'high',
    progress: 0,
    deliverables_remaining: 8,
    sync_status: 'pending',
    in_geofence: false,
    assigned_to: 'j.smith@purpulse.com',
    assigned_name: 'J. Smith',
  },
  {
    id: 'mock-j3',
    title: 'Fiber Backbone Splice & Test',
    company_name: 'City of Denver',
    project_name: 'DEN-FIBER-2026',
    site_name: 'City Hall Comms Room',
    site_address: '1437 Bannock St, Denver CO 80202',
    contact_name: 'Trevor Hollis',
    contact_phone: '720-555-0334',
    scheduled_date: '2026-03-16',
    scheduled_time: '13:00',
    status: 'assigned',
    priority: 'medium',
    progress: 0,
    deliverables_remaining: 6,
    sync_status: 'synced',
    in_geofence: false,
    assigned_to: 'a.jones@purpulse.com',
    assigned_name: 'A. Jones',
  },
  {
    id: 'mock-j4',
    title: 'Critical Care UPS Replacement',
    company_name: "St. Luke's Medical Center",
    project_name: 'STL-UPS-EMER-01',
    site_name: 'ICU Server Room B',
    site_address: '4401 Medical Dr, San Antonio TX 78229',
    contact_name: 'Dr. Patricia Noel',
    contact_phone: '210-555-0561',
    scheduled_date: '2026-03-17',
    scheduled_time: '07:00',
    status: 'paused',
    priority: 'urgent',
    progress: 40,
    deliverables_remaining: 5,
    sync_status: 'error',
    in_geofence: false,
    assigned_to: 'j.smith@purpulse.com',
    assigned_name: 'J. Smith',
  },
  {
    id: 'mock-j5',
    title: 'Terminal C LTE Small Cell',
    company_name: 'Dallas Fort Worth Airport',
    project_name: 'DFW-LTE-2026-C',
    site_name: 'DFW Terminal C – Level 2',
    site_address: '2400 Aviation Dr, DFW Airport TX 75261',
    contact_name: 'Keith Farrow',
    contact_phone: '972-555-0728',
    scheduled_date: '2026-03-17',
    scheduled_time: '06:00',
    status: 'checked_in',
    priority: 'high',
    progress: 25,
    deliverables_remaining: 10,
    sync_status: 'synced',
    in_geofence: true,
    assigned_to: 'r.chen@purpulse.com',
    assigned_name: 'R. Chen',
  },
  {
    id: 'mock-j6',
    title: 'Colo Rack Install & Cabling',
    company_name: 'Equinix DA6',
    project_name: 'EQX-DA6-Q1-R12',
    site_name: 'Suite 4B – Row 12',
    site_address: '1950 N Stemmons Fwy, Dallas TX 75207',
    contact_name: 'Angela Park',
    contact_phone: '214-555-0933',
    scheduled_date: '2026-03-15',
    scheduled_time: '22:00',
    status: 'pending_closeout',
    priority: 'medium',
    progress: 90,
    deliverables_remaining: 1,
    sync_status: 'synced',
    in_geofence: false,
    assigned_to: 'r.chen@purpulse.com',
    assigned_name: 'R. Chen',
  },
  {
    id: 'mock-j7',
    title: 'Campus WiFi 6E Upgrade',
    company_name: 'TechNova Inc.',
    project_name: 'TNOVA-WIFI6E-HQ',
    site_name: 'HQ Campus — Building B',
    site_address: '800 Corporate Dr, Plano TX 75024',
    contact_name: 'James Kowalski',
    contact_phone: '469-555-0214',
    scheduled_date: '2026-03-18',
    scheduled_time: '09:00',
    status: 'assigned',
    priority: 'low',
    progress: 0,
    deliverables_remaining: 12,
    sync_status: 'synced',
    in_geofence: false,
    assigned_to: 'a.jones@purpulse.com',
    assigned_name: 'A. Jones',
  },
  {
    id: 'mock-j8',
    title: 'Solar Array Monitoring Network',
    company_name: 'SunPath Energy LLC',
    project_name: 'SUN-HOU-MON-01',
    site_name: 'Warehouse District Array',
    site_address: '5500 Commerce St, Houston TX 77001',
    contact_name: 'Maria Estrada',
    contact_phone: '713-555-0478',
    scheduled_date: '2026-03-14',
    scheduled_time: '08:30',
    status: 'approved',
    priority: 'low',
    progress: 100,
    deliverables_remaining: 0,
    sync_status: 'synced',
    in_geofence: false,
    assigned_to: 'j.smith@purpulse.com',
    assigned_name: 'J. Smith',
  },
];